# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "opscode-centos-6.4"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Package caching to speed up the box bootup and configuration time
  config.cache.auto_detect = true
  config.cache.scope = :box
  config.omnibus.cache_packages = true

  # Disable vbguest plugin updates to speed up box bootup and configuration time
  config.vbguest.auto_update = false

  # Configure the Chef version to use
  config.omnibus.chef_version = "11.16.4"

  # The MHA manager box
  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager.localhost"
    manager.vm.network "private_network", ip: ENV["MHA_MANAGER_HOST_IP"]
    manager.vm.synced_folder "../../../mha-helper", ENV["MHA_HELPER_PATH_ON_VM"]
  end

  # The MySQL master box
  config.vm.define "master" do |master|
    master.vm.hostname = "master.localhost"
    master.vm.network "private_network", ip: ENV["MHA_MASTER_HOST_IP"]
  end

  # The MySQL slave node1 box
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1.localhost"
    node1.vm.network "private_network", ip: ENV["MHA_NODE1_HOST_IP"]
  end

  # The MySQL slave node2 box
  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2.localhost"
    node2.vm.network "private_network", ip: ENV["MHA_NODE2_HOST_IP"]
  end
end
