#!/bin/sh

# (c) 2015, Ovais Tariq <me@ovaistariq.net>
#
# This file is part of mha-helper
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
### BEGIN INIT INFO
# Provides:             mha_manager_daemon-test_cluster
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    This is mha_manager_daemon for test_cluster
# Description:          There can be multiple instances of mha_manager_daemon
#                       running each monitoring a different MySQL master-slave
#                       cluster. The purpose of this init-script is to provide
#                       a controlling the daemon specific to the cluster named
#                       test_cluster.
### END INIT INFO

# Get function from functions library
. /etc/init.d/functions

CONF=/usr/local/mha-helper/conf/test_cluster.conf
MHA_DAEMON=/usr/local/mha-helper/support-files/mha_manager_daemon
SLAVE_CHECK_DAEMON=/usr/local/mha-helper/support-files/slave_health_check_daemon

case "$1" in
    start)
        ${MHA_DAEMON} --conf=${CONF} start
        ${SLAVE_CHECK_DAEMON} start
        ;;
    stop)
        ${MHA_DAEMON} --conf=${CONF} stop
        ${SLAVE_CHECK_DAEMON} stop
        ;;
    status)
        ${MHA_DAEMON} --conf=${CONF} status
        ${SLAVE_CHECK_DAEMON} status
        ;;
    restart)
        ${MHA_DAEMON} --conf=${CONF} restart
        ${SLAVE_CHECK_DAEMON} restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
