Vagrant.configure("2") do |c|
  c.vm.box = "opscode-centos-6.6"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box"
  if Vagrant.has_plugin?("vagrant-cachier")
    c.cache.auto_detect = true
    c.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-omnibus")
    c.omnibus.cache_packages = true
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    c.vbguest.auto_update = false
  end
  c.vm.hostname = "manager.localhost"
  c.vm.network(:private_network, {:ip=>"192.168.30.10"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/ovais.tariq/Documents/work/projects/mha-helper", "/tmp/mha-helper", nil
  c.vm.provider :virtualbox do |p|
  end
end
