#!/usr/bin/env python

import sys
import string
from optparse import OptionParser
from lib.mha_config_helper import MHA_config_helper
from lib.email_helper import Email_helper

def main():
    # parse comand line arguments
    parser = OptionParser()
    parser.add_option('--orig_master_host', type='string')
    parser.add_option('--new_master_host', type='string')
    parser.add_option('--new_slave_hosts', type='string')
    parser.add_option('--subject', type='string')
    parser.add_option('--body', type='string')

    (options, args) = parser.parse_args()

    # do the actual work
    exit_code = 1

    if (options.orig_master_host is None or
        options.new_master_host is None or
        options.new_slave_hosts is None or
        options.subject is None or
        options.body is None) :
        sys.exit(exit_code)

    config_helper = MHA_config_helper(host=options.orig_master_host)
    report_email_list = string.split(s=config_helper.get_report_email(), 
            sep=',')
    
    email_helper = Email_helper()
    email_helper.send_email(subject=options.subject, msg=options.body, 
            to_email_list=report_email_list)
