#!/usr/bin/env python

# (c) 2013, Ovais Tariq <ovaistariq@gmail.com>
#
# This file is part of mha-helper
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import string
from optparse import OptionParser
from lib.mha_config_helper import MHA_config_helper
from lib.email_helper import Email_helper

def main():
    # parse comand line arguments
    parser = OptionParser()
    parser.add_option('--conf', type='string')
    parser.add_option('--orig_master_host', type='string')
    parser.add_option('--new_master_host', type='string')
    parser.add_option('--new_slave_hosts', type='string')
    parser.add_option('--subject', type='string')
    parser.add_option('--body', type='string')

    (options, args) = parser.parse_args()

    # do the actual work
    exit_code = 1

    if (options.orig_master_host is None or
        options.new_master_host is None or
        options.new_slave_hosts is None or
        options.subject is None or
        options.body is None) :
        sys.exit(exit_code)

    config_helper = MHA_config_helper(host=options.orig_master_host)
    report_email_list = string.split(s=config_helper.get_report_email(), 
            sep=',')
    
    email_helper = Email_helper()
    return_val = email_helper.send_email(subject=options.subject, msg=options.body, 
            to_email_list=report_email_list)

    if return_val == True:
        exit_code = 0

    # exit the script with the appropriate code
    sys.exit(exit_code)

if __name__ == "__main__":
    main()
