#!/bin/bash

# (c) 2013, Ovais Tariq <me@ovaistariq.net>
#
# This file is part of mha_helper
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

conf=""

OPTIND=1
while getopts "h?c:" opt; do
    case "$opt" in
        h|\?)
            #show_help
            exit 0
            ;;
        c)  conf=$OPTARG
            ;;
    esac
done
shift $((OPTIND-1)) # Shift off the options and optional --.

if [[ -z "$conf" ]]
then
    echo "ERROR: option '-c CONF' not given. See -h" >&2
    exit 1
fi

if [[ ! -e "$conf" ]]
then
    echo "ERROR: $conf does not exist"
    exit 1
fi


/usr/bin/masterha_master_switch \
--conf=${conf} \
--master_state=alive \
--orig_master_is_new_slave \
--interactive=0
