#!/usr/bin/env python

# (c) 2013, Ovais Tariq <ovaistariq@gmail.com>
#
# This file is part of mha-helper
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import BaseHTTPServer
import socket
from datetime import datetime
from lib.mha_slave_helper import MHA_slave_helper
from lib.mha_config_helper import MHA_config_helper

class Slave_health_check_server(BaseHTTPServer.BaseHTTPRequestHandler):
    # HTTP response codes sent by the server
    HTTP_ERROR_CODE = 503
    HTTP_SUCCESS_CODE = 200

    def __init__(self, request, client_addr, server):
        self._slave_host_port_dict = MHA_config_helper.get_host_slave_health_check_port_dict()

        BaseHTTPServer.BaseHTTPRequestHandler.__init__(
                self, request, client_addr, server)

    def do_OPTIONS(self):
        self.do_GET()

    def do_GET(self):
        slave_hostname = self._get_slave_host()

        # Run the test to see if slave is healthy
        slave = MHA_slave_helper(slave_host=slave_hostname)
        return_code = slave.is_healthy()
        return_message = slave.get_return_code_string(return_code)

        if return_code == MHA_slave_helper.CODE_SUCCESS:
            response_code = Slave_health_check_server.HTTP_SUCCESS_CODE
        else:
            response_code = Slave_health_check_server.HTTP_ERROR_CODE

        # Send back the HTTP response
        try:
            self.send_response(response_code)
            self.send_header("Content-type", "text/html")
            self.end_headers()
            self.wfile.write(return_message)
            self.wfile.write("Serving on port %s" % self.server.server_port )
        except socket.error:
            pass

    def do_QUIT(self):
        """send 200 OK response, and set server.stop to True"""
        self.send_response(200)
        self.end_headers()
        self.server.stop = True

    def finish(self, *args, **kw):
        try:
            if not self.wfile.closed:
                self.wfile.flush()
                self.wfile.close()
        except socket.error:
            pass

        self.rfile.close()

    def _get_slave_host(self):
        server_port = self.server.server_port

        for slave_host, slave_listen_port in self._slave_host_port_dict.iteritems():
            if slave_listen_port == server_port:
                return slave_host

        return False


class StoppableHttpServer(BaseHTTPServer.HTTPServer):
    """http server that reacts to self.stop flag"""

    def serve_forever (self):
        """Handle one request at a time until stopped."""
        self.stop = False
        while not self.stop:
            self.handle_request()

def debug_message(message):
    current_datetime = datetime.now().strftime("%Y-%m-%-d %H:%M:%S")
    print "[%s] %s" % (current_datetime, message)

def main():
    server_class = StoppableHttpServer
    handler_class = Slave_health_check_server

    host_slave_port_dict = MHA_config_helper.get_host_slave_health_check_port_dict()

    for slave_host, slave_listen_port in host_slave_port_dict.iteritems():
        server_address = ('', slave_listen_port)
        httpd = server_class(server_address, handler_class)

        debug_message("slave health_check started listening on port %s" %
                slave_listen_port)

        httpd.serve_forever()

    debug_message("slave_health_check shutting down ... bye")

if __name__ == "__main__":
    main()

